/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime false` (hash: 628b6b7e93c1c651aced6397688657f7)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker-entry");
		durableNamespaces: "AiChatDailySpendCap";
	}
	interface Env {
		RATE_LIMIT: KVNamespace;
		ASSETS: Fetcher;
		DOCS_SITE_URL: "https://zudo-doc.takazudomodular.com";
		RATE_LIMIT_PER_MINUTE: "10";
		RATE_LIMIT_PER_DAY: "100";
		AI_CHAT_DAILY_SPEND_CAP: DurableObjectNamespace<import("./worker-entry").AiChatDailySpendCap>;
	}
}
interface Env extends Cloudflare.Env {}
