import { describe, it, expect } from "vitest";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

// Import the generator functions directly so the test exercises the same
// logic the CLI uses, without needing a built dist or running Node as a child.
// The .mjs is plain ESM with no Node built-ins called at import time (only
// in main()), so dynamic import works fine from vitest's ESM environment.
const __dirname = dirname(fileURLToPath(import.meta.url));

// Import via relative path that steps outside src/ into bin/.
// Vitest resolves this at test time; it is NOT compiled by tsup.
const { parseTokens, groupBySelector, buildBlock, replaceBlock } = await import(
  resolve(__dirname, "../../bin/gen-component-tokens.mjs")
);

// ── helpers ────────────────────────────────────────────────────────────────

/** Minimal content.css shell with BEGIN/END markers. */
function wrapInCss(inner: string): string {
  return `/* preamble */\n\n${inner}\n`;
}

const BEGIN_MARKER =
  "/* BEGIN --zdc-* component tokens (generated by gen-component-tokens; do not edit by hand) */";
const END_MARKER = "/* END --zdc-* component tokens */";

// ── parseTokens ────────────────────────────────────────────────────────────

describe("parseTokens", () => {
  it("extracts all required fields from a well-formed source", () => {
    const src = `
export const COMPONENT_TOKENS: ComponentToken[] = [
  {
    cssVar: "--zdc-doc-title-font",
    selector: "h1.text-heading",
    property: "font-family",
    default: "inherit",
    component: "doc-title",
    category: "typography",
    description: "Some description.",
  },
];`;
    const tokens = parseTokens(src);
    expect(tokens).toHaveLength(1);
    expect(tokens[0]).toMatchObject({
      cssVar: "--zdc-doc-title-font",
      selector: "h1.text-heading",
      property: "font-family",
      default: "inherit",
    });
  });

  it("extracts a default value containing var() (nested parentheses)", () => {
    const src = `
export const COMPONENT_TOKENS: ComponentToken[] = [
  {
    cssVar: "--zdc-doc-title-weight",
    selector: "h1.text-heading",
    property: "font-weight",
    default: "var(--font-weight-bold)",
    component: "doc-title",
    category: "typography",
    description: "Some description.",
  },
];`;
    const tokens = parseTokens(src);
    expect(tokens[0].default).toBe("var(--font-weight-bold)");
  });

  it("extracts multiple tokens in source order", () => {
    const src = `
export const COMPONENT_TOKENS: ComponentToken[] = [
  {
    cssVar: "--zdc-a",
    selector: "h1",
    property: "color",
    default: "red",
    component: "foo",
    category: "typography",
    description: "A.",
  },
  {
    cssVar: "--zdc-b",
    selector: "h1",
    property: "font-size",
    default: "inherit",
    component: "foo",
    category: "typography",
    description: "B.",
  },
];`;
    const tokens = parseTokens(src);
    expect(tokens).toHaveLength(2);
    expect(tokens[0].cssVar).toBe("--zdc-a");
    expect(tokens[1].cssVar).toBe("--zdc-b");
  });

  it("throws when the COMPONENT_TOKENS export is absent", () => {
    const src = `export const OTHER = [];`;
    expect(() => parseTokens(src)).toThrow(/COMPONENT_TOKENS/);
  });

  it("throws when a token object is missing a required field", () => {
    const src = `
export const COMPONENT_TOKENS: ComponentToken[] = [
  {
    cssVar: "--zdc-x",
    selector: "h1",
    property: "color",
    // default is missing
    component: "foo",
    category: "typography",
    description: "X.",
  },
];`;
    expect(() => parseTokens(src)).toThrow(/missing cssVar\/selector\/property\/default/);
  });

  it("throws when COMPONENT_TOKENS is empty", () => {
    const src = `export const COMPONENT_TOKENS: ComponentToken[] = [];`;
    expect(() => parseTokens(src)).toThrow(/empty list/);
  });
});

// ── groupBySelector ────────────────────────────────────────────────────────

describe("groupBySelector", () => {
  it("groups tokens by selector, preserving insertion order of selectors", () => {
    const tokens = [
      { cssVar: "--a", selector: "h1", property: "color", default: "red" },
      { cssVar: "--b", selector: "h1", property: "font-size", default: "inherit" },
      { cssVar: "--c", selector: "p", property: "color", default: "blue" },
    ];
    const groups = groupBySelector(tokens);
    const keys = [...groups.keys()];
    expect(keys).toEqual(["h1", "p"]);
    expect(groups.get("h1")).toHaveLength(2);
    expect(groups.get("p")).toHaveLength(1);
  });

  it("preserves within-selector declaration order", () => {
    const tokens = [
      { cssVar: "--a", selector: "h1", property: "color", default: "red" },
      { cssVar: "--b", selector: "h1", property: "font-weight", default: "bold" },
    ];
    const groups = groupBySelector(tokens);
    const entries = groups.get("h1")!;
    expect(entries[0].cssVar).toBe("--a");
    expect(entries[1].cssVar).toBe("--b");
  });
});

// ── buildBlock ─────────────────────────────────────────────────────────────

describe("buildBlock", () => {
  it("wraps output with BEGIN and END markers", () => {
    const tokens = [
      { cssVar: "--zdc-x", selector: "h1", property: "color", default: "red" },
    ];
    const block = buildBlock(tokens);
    expect(block).toContain(BEGIN_MARKER);
    expect(block).toContain(END_MARKER);
    expect(block.indexOf(BEGIN_MARKER)).toBeLessThan(block.indexOf(END_MARKER));
  });

  it("emits one rule per selector", () => {
    const tokens = [
      { cssVar: "--zdc-a", selector: "h1", property: "color", default: "red" },
      { cssVar: "--zdc-b", selector: "h1", property: "font-weight", default: "bold" },
      { cssVar: "--zdc-c", selector: "p", property: "color", default: "blue" },
    ];
    const block = buildBlock(tokens);
    // Count occurrences of "h1 {" and "p {"
    expect(block.split("h1 {")).toHaveLength(2); // 1 match → splits into 2 parts
    expect(block.split("p {")).toHaveLength(2);
  });

  it("emits var() declarations with correct cssVar and default", () => {
    const tokens = [
      { cssVar: "--zdc-doc-title-font", selector: "h1.text-heading", property: "font-family", default: "inherit" },
      { cssVar: "--zdc-doc-title-weight", selector: "h1.text-heading", property: "font-weight", default: "var(--font-weight-bold)" },
    ];
    const block = buildBlock(tokens);
    expect(block).toContain("  font-family: var(--zdc-doc-title-font, inherit);");
    expect(block).toContain("  font-weight: var(--zdc-doc-title-weight, var(--font-weight-bold));");
  });

  it("produces output that ends at the END marker (no trailing newline)", () => {
    const tokens = [
      { cssVar: "--zdc-x", selector: "h1", property: "color", default: "red" },
    ];
    const block = buildBlock(tokens);
    expect(block.endsWith(END_MARKER)).toBe(true);
  });
});

// ── replaceBlock ───────────────────────────────────────────────────────────

describe("replaceBlock", () => {
  it("replaces the block between BEGIN and END markers", () => {
    const existing = wrapInCss(
      `${BEGIN_MARKER}\n\nh1 { color: old; }\n\n${END_MARKER}`,
    );
    const tokens = [
      { cssVar: "--zdc-x", selector: "h1", property: "color", default: "new" },
    ];
    const next = replaceBlock(existing, buildBlock(tokens));
    expect(next).toContain("var(--zdc-x, new)");
    expect(next).not.toContain("old");
  });

  it("throws when BEGIN marker is absent", () => {
    const css = `/* no markers here */\n`;
    const block = `${BEGIN_MARKER}\n\n${END_MARKER}`;
    expect(() => replaceBlock(css, block)).toThrow(/BEGIN\/END markers/);
  });

  it("preserves surrounding content outside the block", () => {
    const prefix = "/* prefix content */\n\n";
    const suffix = "\n/* suffix content */\n";
    const css = `${prefix}${BEGIN_MARKER}\n\nh1 { color: old; }\n\n${END_MARKER}${suffix}`;
    const tokens = [
      { cssVar: "--zdc-x", selector: "h1", property: "color", default: "new" },
    ];
    const next = replaceBlock(css, buildBlock(tokens));
    expect(next.startsWith(prefix)).toBe(true);
    expect(next).toContain(suffix);
  });
});

// ── Idempotency ────────────────────────────────────────────────────────────

describe("Idempotency", () => {
  it("running buildBlock + replaceBlock twice produces no diff", () => {
    const initial = wrapInCss(
      `${BEGIN_MARKER}\n\nh1 { color: old; }\n\n${END_MARKER}`,
    );
    const tokens = [
      { cssVar: "--zdc-doc-title-font", selector: "h1.text-heading", property: "font-family", default: "inherit" },
      { cssVar: "--zdc-doc-title-weight", selector: "h1.text-heading", property: "font-weight", default: "var(--font-weight-bold)" },
    ];
    const first = replaceBlock(initial, buildBlock(tokens));
    const second = replaceBlock(first, buildBlock(tokens));
    expect(second).toBe(first);
  });
});

// ── Automated default-value test (addendum from #2448) ────────────────────
//
// For every entry in COMPONENT_TOKENS, assert the generated content.css block
// contains the expected `<selector> { <property>: var(<cssVar>, <default>); }`
// with the correct fallback. This codifies the defaults in test so any future
// change to the token data (e.g. wrong default) is caught mechanically.

describe("Default-value test — generated content.css block", () => {
  const PKG_ROOT = resolve(__dirname, "../../");
  const tokensSrc = readFileSync(
    resolve(PKG_ROOT, "src/config/component-tokens.ts"),
    "utf8",
  );
  const contentCss = readFileSync(
    resolve(PKG_ROOT, "src/content.css"),
    "utf8",
  );

  const tokens = parseTokens(tokensSrc);

  it("every COMPONENT_TOKENS entry has its expected declaration in content.css", () => {
    for (const token of tokens) {
      const expected = `  ${token.property}: var(${token.cssVar}, ${token.default});`;
      expect(contentCss).toContain(expected);
    }
  });

  it("content.css block matches the freshly-generated block (no drift)", () => {
    const generated = buildBlock(tokens);
    // The generated block should appear verbatim inside content.css.
    expect(contentCss).toContain(generated);
  });

  // Spot-check each known token in the current registry so regressions in
  // specific defaults surface with a clear error message.
  it("--zdc-doc-title-font defaults to inherit", () => {
    expect(contentCss).toContain(
      "  font-family: var(--zdc-doc-title-font, inherit);",
    );
  });

  it("--zdc-doc-title-weight defaults to var(--font-weight-bold)", () => {
    expect(contentCss).toContain(
      "  font-weight: var(--zdc-doc-title-weight, var(--font-weight-bold));",
    );
  });
});
