import { describe, it, expect } from "vitest";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { readFileSync } from "node:fs";

// Import the generator functions directly so the test exercises the same
// logic the CLI uses, without needing a built dist or running Node as a child.
// The .mjs is plain ESM with no Node built-ins called at import time (only
// in main()), so dynamic import works fine from vitest's ESM environment.
const __dirname = dirname(fileURLToPath(import.meta.url));

// Import via relative path that steps outside src/ into bin/.
// Vitest resolves this at test time; it is NOT compiled by tsup.
const { parseTokens, groupBySelector, routeBySurface, buildBlock, replaceBlock } =
  await import(resolve(__dirname, "../../bin/gen-component-tokens.mjs"));

// ── helpers ────────────────────────────────────────────────────────────────

/** Minimal content.css shell with BEGIN/END markers. */
function wrapInCss(inner: string): string {
  return `/* preamble */\n\n${inner}\n`;
}

const BEGIN_MARKER =
  "/* BEGIN --zdc-* component tokens (generated by gen-component-tokens; do not edit by hand) */";
const END_MARKER = "/* END --zdc-* component tokens */";

const CHROME_BEGIN_MARKER =
  "/* BEGIN --zdc-* chrome component tokens (generated by gen-component-tokens; do not edit by hand) */";
const CHROME_END_MARKER = "/* END --zdc-* chrome component tokens */";

// ── parseTokens ────────────────────────────────────────────────────────────

describe("parseTokens", () => {
  it("extracts all required fields from a well-formed source", () => {
    const src = `
export const COMPONENT_TOKENS: ComponentToken[] = [
  {
    cssVar: "--zdc-doc-title-font",
    selector: "h1.text-heading",
    property: "font-family",
    default: "inherit",
    component: "doc-title",
    surface: "content",
    category: "typography",
    description: "Some description.",
  },
];`;
    const tokens = parseTokens(src);
    expect(tokens).toHaveLength(1);
    expect(tokens[0]).toMatchObject({
      cssVar: "--zdc-doc-title-font",
      selector: "h1.text-heading",
      property: "font-family",
      default: "inherit",
      surface: "content",
    });
  });

  it("extracts a default value containing var() (nested parentheses)", () => {
    const src = `
export const COMPONENT_TOKENS: ComponentToken[] = [
  {
    cssVar: "--zdc-doc-title-weight",
    selector: "h1.text-heading",
    property: "font-weight",
    default: "var(--font-weight-bold)",
    component: "doc-title",
    surface: "content",
    category: "typography",
    description: "Some description.",
  },
];`;
    const tokens = parseTokens(src);
    expect(tokens[0].default).toBe("var(--font-weight-bold)");
  });

  it("extracts multiple tokens in source order", () => {
    const src = `
export const COMPONENT_TOKENS: ComponentToken[] = [
  {
    cssVar: "--zdc-a",
    selector: "h1",
    property: "color",
    default: "red",
    component: "foo",
    surface: "content",
    category: "typography",
    description: "A.",
  },
  {
    cssVar: "--zdc-b",
    selector: "h1",
    property: "font-size",
    default: "inherit",
    component: "foo",
    surface: "content",
    category: "typography",
    description: "B.",
  },
];`;
    const tokens = parseTokens(src);
    expect(tokens).toHaveLength(2);
    expect(tokens[0].cssVar).toBe("--zdc-a");
    expect(tokens[1].cssVar).toBe("--zdc-b");
  });

  it("throws when the COMPONENT_TOKENS export is absent", () => {
    const src = `export const OTHER = [];`;
    expect(() => parseTokens(src)).toThrow(/COMPONENT_TOKENS/);
  });

  it("throws when a token object is missing a required field", () => {
    const src = `
export const COMPONENT_TOKENS: ComponentToken[] = [
  {
    cssVar: "--zdc-x",
    selector: "h1",
    property: "color",
    // default is missing
    component: "foo",
    surface: "content",
    category: "typography",
    description: "X.",
  },
];`;
    expect(() => parseTokens(src)).toThrow(/missing cssVar\/selector\/property\/default/);
  });

  it("throws when a token is missing the required surface field", () => {
    const src = `
export const COMPONENT_TOKENS: ComponentToken[] = [
  {
    cssVar: "--zdc-no-surface",
    selector: "h1",
    property: "color",
    default: "inherit",
    component: "foo",
    category: "typography",
    description: "No surface.",
  },
];`;
    expect(() => parseTokens(src)).toThrow(/missing the required "surface" field/);
  });

  it("throws when COMPONENT_TOKENS is empty", () => {
    const src = `export const COMPONENT_TOKENS: ComponentToken[] = [];`;
    expect(() => parseTokens(src)).toThrow(/empty list/);
  });
});

// ── groupBySelector ────────────────────────────────────────────────────────

describe("groupBySelector", () => {
  it("groups tokens by selector, preserving insertion order of selectors", () => {
    const tokens = [
      { cssVar: "--a", selector: "h1", property: "color", default: "red" },
      { cssVar: "--b", selector: "h1", property: "font-size", default: "inherit" },
      { cssVar: "--c", selector: "p", property: "color", default: "blue" },
    ];
    const groups = groupBySelector(tokens);
    const keys = [...groups.keys()];
    expect(keys).toEqual(["h1", "p"]);
    expect(groups.get("h1")).toHaveLength(2);
    expect(groups.get("p")).toHaveLength(1);
  });

  it("preserves within-selector declaration order", () => {
    const tokens = [
      { cssVar: "--a", selector: "h1", property: "color", default: "red" },
      { cssVar: "--b", selector: "h1", property: "font-weight", default: "bold" },
    ];
    const groups = groupBySelector(tokens);
    const entries = groups.get("h1")!;
    expect(entries[0].cssVar).toBe("--a");
    expect(entries[1].cssVar).toBe("--b");
  });
});

// ── routeBySurface ─────────────────────────────────────────────────────────

describe("routeBySurface", () => {
  it("partitions tokens into content and chrome buckets", () => {
    const tokens = [
      { cssVar: "--zdc-a", selector: "h1", property: "color", default: "red", surface: "content" },
      { cssVar: "--zdc-b", selector: "header", property: "color", default: "blue", surface: "chrome" },
      { cssVar: "--zdc-c", selector: "h2", property: "color", default: "green", surface: "content" },
    ];
    const routes = routeBySurface(tokens);
    expect(routes.get("content").map((t: { cssVar: string }) => t.cssVar)).toEqual([
      "--zdc-a",
      "--zdc-c",
    ]);
    expect(routes.get("chrome").map((t: { cssVar: string }) => t.cssVar)).toEqual([
      "--zdc-b",
    ]);
  });

  it("always returns a bucket for every known surface, even when empty", () => {
    const tokens = [
      { cssVar: "--zdc-a", selector: "h1", property: "color", default: "red", surface: "content" },
    ];
    const routes = routeBySurface(tokens);
    expect(routes.has("content")).toBe(true);
    expect(routes.has("chrome")).toBe(true);
    expect(routes.get("chrome")).toHaveLength(0);
  });

  it("throws on an unknown surface value", () => {
    const tokens = [
      { cssVar: "--zdc-x", selector: "h1", property: "color", default: "red", surface: "sidebar" },
    ];
    expect(() => routeBySurface(tokens)).toThrow(/unknown surface "sidebar"/);
  });
});

// ── buildBlock ─────────────────────────────────────────────────────────────

describe("buildBlock", () => {
  it("wraps output with BEGIN and END markers", () => {
    const tokens = [
      { cssVar: "--zdc-x", selector: "h1", property: "color", default: "red" },
    ];
    const block = buildBlock(tokens);
    expect(block).toContain(BEGIN_MARKER);
    expect(block).toContain(END_MARKER);
    expect(block.indexOf(BEGIN_MARKER)).toBeLessThan(block.indexOf(END_MARKER));
  });

  it("emits one rule per selector", () => {
    const tokens = [
      { cssVar: "--zdc-a", selector: "h1", property: "color", default: "red" },
      { cssVar: "--zdc-b", selector: "h1", property: "font-weight", default: "bold" },
      { cssVar: "--zdc-c", selector: "p", property: "color", default: "blue" },
    ];
    const block = buildBlock(tokens);
    // Count occurrences of "h1 {" and "p {"
    expect(block.split("h1 {")).toHaveLength(2); // 1 match → splits into 2 parts
    expect(block.split("p {")).toHaveLength(2);
  });

  it("emits var() declarations with correct cssVar and default", () => {
    const tokens = [
      { cssVar: "--zdc-doc-title-font", selector: "h1.text-heading", property: "font-family", default: "inherit" },
      { cssVar: "--zdc-doc-title-weight", selector: "h1.text-heading", property: "font-weight", default: "var(--font-weight-bold)" },
    ];
    const block = buildBlock(tokens);
    expect(block).toContain("  font-family: var(--zdc-doc-title-font, inherit);");
    expect(block).toContain("  font-weight: var(--zdc-doc-title-weight, var(--font-weight-bold));");
  });

  it("produces output that ends at the END marker (no trailing newline)", () => {
    const tokens = [
      { cssVar: "--zdc-x", selector: "h1", property: "color", default: "red" },
    ];
    const block = buildBlock(tokens);
    expect(block.endsWith(END_MARKER)).toBe(true);
  });

  it("honours a custom marker pair (chrome surface)", () => {
    const tokens = [
      { cssVar: "--zdc-header-bg", selector: "header", property: "background", default: "inherit" },
    ];
    const block = buildBlock(tokens, CHROME_BEGIN_MARKER, CHROME_END_MARKER);
    expect(block.startsWith(CHROME_BEGIN_MARKER)).toBe(true);
    expect(block.endsWith(CHROME_END_MARKER)).toBe(true);
    expect(block).not.toContain(BEGIN_MARKER);
  });

  it("yields just the marker pair for an empty token list (seeded chrome block)", () => {
    const block = buildBlock([], CHROME_BEGIN_MARKER, CHROME_END_MARKER);
    expect(block).toBe(`${CHROME_BEGIN_MARKER}\n\n${CHROME_END_MARKER}`);
  });
});

// ── replaceBlock ───────────────────────────────────────────────────────────

describe("replaceBlock", () => {
  it("replaces the block between BEGIN and END markers", () => {
    const existing = wrapInCss(
      `${BEGIN_MARKER}\n\nh1 { color: old; }\n\n${END_MARKER}`,
    );
    const tokens = [
      { cssVar: "--zdc-x", selector: "h1", property: "color", default: "new" },
    ];
    const next = replaceBlock(existing, buildBlock(tokens));
    expect(next).toContain("var(--zdc-x, new)");
    expect(next).not.toContain("old");
  });

  it("throws when BEGIN marker is absent", () => {
    const css = `/* no markers here */\n`;
    const block = `${BEGIN_MARKER}\n\n${END_MARKER}`;
    expect(() => replaceBlock(css, block)).toThrow(/BEGIN\/END markers/);
  });

  it("preserves surrounding content outside the block", () => {
    const prefix = "/* prefix content */\n\n";
    const suffix = "\n/* suffix content */\n";
    const css = `${prefix}${BEGIN_MARKER}\n\nh1 { color: old; }\n\n${END_MARKER}${suffix}`;
    const tokens = [
      { cssVar: "--zdc-x", selector: "h1", property: "color", default: "new" },
    ];
    const next = replaceBlock(css, buildBlock(tokens));
    expect(next.startsWith(prefix)).toBe(true);
    expect(next).toContain(suffix);
  });
});

// ── Idempotency ────────────────────────────────────────────────────────────

describe("Idempotency", () => {
  it("running buildBlock + replaceBlock twice produces no diff", () => {
    const initial = wrapInCss(
      `${BEGIN_MARKER}\n\nh1 { color: old; }\n\n${END_MARKER}`,
    );
    const tokens = [
      { cssVar: "--zdc-doc-title-font", selector: "h1.text-heading", property: "font-family", default: "inherit" },
      { cssVar: "--zdc-doc-title-weight", selector: "h1.text-heading", property: "font-weight", default: "var(--font-weight-bold)" },
    ];
    const first = replaceBlock(initial, buildBlock(tokens));
    const second = replaceBlock(first, buildBlock(tokens));
    expect(second).toBe(first);
  });
});

// ── Automated default-value test (addendum from #2448) ────────────────────
//
// For every entry in COMPONENT_TOKENS, assert the generated content.css block
// contains the expected `<selector> { <property>: var(<cssVar>, <default>); }`
// with the correct fallback. This codifies the defaults in test so any future
// change to the token data (e.g. wrong default) is caught mechanically.

describe("Default-value test — generated content.css block", () => {
  const PKG_ROOT = resolve(__dirname, "../../");
  const tokensSrc = readFileSync(
    resolve(PKG_ROOT, "src/config/component-tokens.ts"),
    "utf8",
  );
  const contentCss = readFileSync(
    resolve(PKG_ROOT, "src/content.css"),
    "utf8",
  );
  const featuresCss = readFileSync(
    resolve(PKG_ROOT, "src/features.css"),
    "utf8",
  );

  const tokens = parseTokens(tokensSrc);
  const routes = routeBySurface(tokens);
  const contentTokens = routes.get("content");
  const chromeTokens = routes.get("chrome");

  it("every content-surface token has its expected declaration in content.css", () => {
    for (const token of contentTokens) {
      const expected = `  ${token.property}: var(${token.cssVar}, ${token.default});`;
      expect(contentCss).toContain(expected);
    }
  });

  it("content.css block matches the freshly-generated content block (no drift)", () => {
    const generated = buildBlock(contentTokens);
    // The generated block should appear verbatim inside content.css.
    expect(contentCss).toContain(generated);
  });

  it("features.css chrome block matches the freshly-generated chrome block (no drift)", () => {
    const generated = buildBlock(
      chromeTokens,
      CHROME_BEGIN_MARKER,
      CHROME_END_MARKER,
    );
    expect(featuresCss).toContain(generated);
  });

  it("12 tokens route to content; 9 chrome tokens after the #2887 font seam", () => {
    expect(contentTokens).toHaveLength(12);
    expect(chromeTokens).toHaveLength(9);
  });

  // The compiled proof of the chrome font seam (#2887): the generated rule must
  // reach features.css verbatim, or a theme pack's `--font-sans` never escapes
  // `.zd-content` and the whole epic's premise breaks.
  it("--zdc-chrome-font emits the body font seam into features.css", () => {
    expect(featuresCss).toContain("body {");
    expect(featuresCss).toContain(
      "  font-family: var(--zdc-chrome-font, var(--font-sans));",
    );
  });

  it("per-surface chrome font knobs emit rules covering desktop + mobile emitters", () => {
    expect(featuresCss).toContain("header[data-header] {");
    expect(featuresCss).toContain("#desktop-sidebar, aside[data-zd-mobile-sidebar] {");
    expect(featuresCss).toContain("nav[data-zd-toc], div[data-zd-mobile-toc] {");
  });

  // Each per-surface knob must fall back to the chrome seam, NOT to `inherit`.
  // `inherit` resolves against whatever ancestor the component happens to sit
  // under, which splits a surface's two emitters: the mobile drawer renders
  // inside `header[data-header]`, so a header-only override would leak into it
  // while `#desktop-sidebar` kept the body font; and the mobile TOC renders
  // inside `.zd-content`, so it would follow the prose font while the desktop
  // rail followed chrome. Pinned because the bug is invisible until a pack
  // overrides exactly one surface.
  it("per-surface chrome font knobs fall back to the chrome seam, never to inherit", () => {
    for (const name of ["--zdc-header-font", "--zdc-sidebar-font", "--zdc-toc-font"]) {
      expect(featuresCss).toContain(
        `  font-family: var(${name}, var(--zdc-chrome-font, var(--font-sans)));`,
      );
      expect(featuresCss).not.toContain(`var(${name}, inherit)`);
    }
  });

  // Spot-check each known token in the current registry so regressions in
  // specific defaults surface with a clear error message.
  it("--zdc-doc-title-font defaults to inherit", () => {
    expect(contentCss).toContain(
      "  font-family: var(--zdc-doc-title-font, inherit);",
    );
  });

  it("--zdc-doc-title-weight defaults to var(--font-weight-bold)", () => {
    expect(contentCss).toContain(
      "  font-weight: var(--zdc-doc-title-weight, var(--font-weight-bold));",
    );
  });

  it("--zdc-nav-active-indicator-color defaults to var(--color-fg) in features.css", () => {
    expect(featuresCss).toContain(
      "  background-color: var(--zdc-nav-active-indicator-color, var(--color-fg));",
    );
  });

  it("--zdc-nav-active-weight defaults to var(--font-weight-medium) in features.css", () => {
    expect(featuresCss).toContain(
      "  font-weight: var(--zdc-nav-active-weight, var(--font-weight-medium));",
    );
  });
});
