// Structural tests for the three package-root artifacts shipped for
// downstream project tsconfigs (#2656): `tsconfig.base.json` and
// `zfb-config-shim.d.ts` (hand-authored, checked into git) plus
// `virtual-modules.d.ts` (GENERATED from `src/routes/_virtual.d.ts` by
// `scripts/copy-virtual-modules.mjs` in the tsup onSuccess chain — requires
// a package build first, which the root `pnpm test` runs; same dependency
// the route-injection tests have on `dist/`). This suite pins their SHAPE —
// the same properties `scripts/check-shim-artifacts.mjs` and
// `scripts/check-virtual-modules.mjs` guard at prepack time, run here as
// fast unit tests so a regression surfaces in `pnpm test`, not only at
// publish time. Consumer-level regression proof (tsc/`zfb check` against a
// fixture project extending tsconfig.base.json, exercising the rewritten
// `import("@takazudo/zudo-doc/factory-context")` specifier end-to-end) is
// the Wave-5 confirm case, zudolab/zudo-doc#2659.

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, "../..");

function read(rel: string): string {
  return readFileSync(resolve(PKG_ROOT, rel), "utf-8");
}

describe("tsconfig.base.json (#2656)", () => {
  const base = JSON.parse(read("tsconfig.base.json"));

  it("has no top-level include/exclude (Q5 trap: files/include/exclude are override-only across extends)", () => {
    expect(base).not.toHaveProperty("include");
    expect(base).not.toHaveProperty("exclude");
    expect(base.compilerOptions).toBeTypeOf("object");
  });

  it("does NOT nest `files` inside compilerOptions (TS5023 — files is a top-level tsconfig field)", () => {
    expect(base.compilerOptions).not.toHaveProperty("files");
  });

  it("ships the two ambient shims via the TOP-LEVEL files field (NOT include)", () => {
    expect(base.files).toEqual(["./zfb-config-shim.d.ts", "./virtual-modules.d.ts"]);
  });

  it("carries the strict + noImplicit* flag set", () => {
    expect(base.compilerOptions.strict).toBe(true);
    expect(base.compilerOptions.noImplicitAny).toBe(true);
    expect(base.compilerOptions.strictNullChecks).toBe(true);
    expect(base.compilerOptions.strictFunctionTypes).toBe(true);
    expect(base.compilerOptions.strictBindCallApply).toBe(true);
    expect(base.compilerOptions.strictPropertyInitialization).toBe(true);
    expect(base.compilerOptions.noImplicitThis).toBe(true);
    expect(base.compilerOptions.useUnknownInCatchVariables).toBe(true);
    expect(base.compilerOptions.alwaysStrict).toBe(true);
  });

  it("carries the bundler/module flag set matching the pre-package-first template", () => {
    expect(base.compilerOptions.target).toBe("ESNext");
    expect(base.compilerOptions.module).toBe("ESNext");
    expect(base.compilerOptions.moduleResolution).toBe("Bundler");
    expect(base.compilerOptions.jsx).toBe("preserve");
    expect(base.compilerOptions.baseUrl).toBe(".");
  });

  it("does NOT carry the react/react-dom/@/* paths block (GOTCHA resolution: base-relative paths would resolve inside node_modules, not the consumer project root — paths stay in the PROJECT tsconfig, see packages/zudo-doc/CLAUDE.md)", () => {
    expect(base.compilerOptions.paths).toBeUndefined();
  });

  it("does NOT carry #doc-history-meta (dropped from the minimal floor per spike Q6 — nothing package-owned imports it)", () => {
    const raw = read("tsconfig.base.json");
    expect(raw).not.toContain("doc-history-meta");
  });
});

describe("zfb-config-shim.d.ts (#2656)", () => {
  const shim = read("zfb-config-shim.d.ts");

  it("declares the bare `zfb/config` module", () => {
    expect(shim).toContain('declare module "zfb/config"');
  });

  it("exports ZfbConfig and defineConfig", () => {
    expect(shim).toContain("export interface ZfbConfig");
    expect(shim).toContain("export function defineConfig(config: ZfbConfig): ZfbConfig;");
  });

  it("documents the hand-sync duty against the published @takazudo/zfb/config", () => {
    expect(shim).toMatch(/kept in sync BY HAND/);
  });
});

describe("virtual-modules.d.ts (#2656 — generated by copy-virtual-modules.mjs)", () => {
  const virtualModules = read("virtual-modules.d.ts");

  it("carries the GENERATED banner naming its source and generator", () => {
    expect(virtualModules).toContain("GENERATED FILE — DO NOT EDIT");
    expect(virtualModules).toContain("src/routes/_virtual.d.ts");
    expect(virtualModules).toContain("copy-virtual-modules.mjs");
  });

  it("declares virtual:zudo-doc-route-context with the serializable-payload shape", () => {
    expect(virtualModules).toContain('declare module "virtual:zudo-doc-route-context"');
    expect(virtualModules).toContain("export const routeContext:");
    expect(virtualModules).toContain("settings: unknown;");
    expect(virtualModules).toContain("translations: Record<string, Record<string, string>>;");
    expect(virtualModules).toContain("tagVocabulary: ReadonlyArray<Record<string, unknown>>;");
    expect(virtualModules).toContain("colorSchemes: Record<string, unknown> | null;");
  });

  it("declares virtual:zudo-doc-chrome-bindings with the import(...) specifier REWRITTEN to the bare package subpath", () => {
    expect(virtualModules).toContain('declare module "virtual:zudo-doc-chrome-bindings"');
    expect(virtualModules).toContain(
      'export const chromeBindings: import("@takazudo/zudo-doc/factory-context").ChromeHostBindings;',
    );
    // No parent-relative import(...) may survive the rewrite — it would
    // dangle from the package root in a consumer's node_modules.
    expect(virtualModules).not.toMatch(/import\s*\(\s*["']\.\.\//);
  });

  it("stays in sync with the source of truth (same declare-module blocks modulo the rewritten specifier)", () => {
    const source = read("src/routes/_virtual.d.ts");
    const rewrittenSource = source.replace(
      'import("../factory-context/index.js")',
      'import("@takazudo/zudo-doc/factory-context")',
    );
    // The generated file is banner + rewritten source, byte-for-byte.
    expect(virtualModules.endsWith(rewrittenSource)).toBe(true);
  });
});

describe("package.json wiring for the three shipped artifacts (#2656)", () => {
  const pkg = JSON.parse(read("package.json"));

  it("lists all three files in the npm publish files[] array", () => {
    expect(pkg.files).toEqual(
      expect.arrayContaining(["tsconfig.base.json", "zfb-config-shim.d.ts", "virtual-modules.d.ts"]),
    );
  });

  it("exposes all three as root-relative (not dist/) exports subpaths", () => {
    expect(pkg.exports["./tsconfig.base.json"]).toBe("./tsconfig.base.json");
    expect(pkg.exports["./zfb-config-shim.d.ts"]).toBe("./zfb-config-shim.d.ts");
    expect(pkg.exports["./virtual-modules.d.ts"]).toBe("./virtual-modules.d.ts");
  });

  it("runs both new guards in prepack", () => {
    expect(pkg.scripts.prepack).toContain("check-shim-artifacts.mjs");
    expect(pkg.scripts.prepack).toContain("check-virtual-modules.mjs");
  });

  it("generates virtual-modules.d.ts in the tsup onSuccess chain", () => {
    const tsupConfig = read("tsup.config.ts");
    expect(tsupConfig).toContain("copy-virtual-modules.mjs");
  });
});
