// Ambient typing for the route-context virtual module emitted by the routes
// plugin (`addVirtualModule("virtual:zudo-doc-route-context", …)`). The module
// has no on-disk source — it is materialised at build by the zfb plugin runtime
// — so this declaration gives the package route entrypoints a typed import.
//
// The payload is SERIALIZABLE DATA ONLY (ADR Decision 1): `settings`,
// `translations`, `tagVocabulary`, `colorSchemes`. `_context.ts` narrows it
// to the concrete `RouteContextPayload` at the seam.
//
// SINGLE SOURCE OF TRUTH for three shipped copies (#2656) — edit HERE only:
//   1. This file itself — typechecks the package's own `src/routes/*.tsx`.
//   2. `routes-src/_virtual.d.ts` — copied by `scripts/copy-routes-src.mjs`
//      for downstream `packageOwnedRoutes` consumers.
//   3. `<package root>/virtual-modules.d.ts` — GENERATED by
//      `scripts/copy-virtual-modules.mjs` (tsup onSuccess; gitignored like
//      `routes-src/`), shipped via `tsconfig.base.json`'s `files` so a HOST
//      project that imports these virtual modules directly (e.g. a `pages/`
//      re-export stub calling `createRouteContext(routeContext)`) typechecks.
// Both copy steps rewrite parent-relative `import(...)` specifiers to bare
// `@takazudo/zudo-doc/*` subpaths, so the relative specifier below stays
// correct here while the shipped copies resolve from a consumer's
// node_modules.
declare module "virtual:zudo-doc-route-context" {
  export const routeContext: {
    settings: unknown;
    translations: Record<string, Record<string, string>>;
    tagVocabulary: ReadonlyArray<Record<string, unknown>>;
    /** Host color-scheme palette map. `null` when the caller did not pass
     *  `colorSchemes` to `zudoDocPreset` — `_chrome.tsx` falls back to
     *  `DEFAULT_SCHEME` in that case. */
    colorSchemes: Record<string, unknown> | null;
  };
}

// Ambient typing for the chrome-bindings virtual module emitted by the routes
// plugin (`addVirtualModule("virtual:zudo-doc-chrome-bindings", …)`, #2501).
// No on-disk source — materialised at build, either as a re-export of the
// host's `settings.chromeBindingsModule` file or as an empty-object fallback
// when the setting is absent. See `plugins/routes.ts` and
// `docs/adr/route-injection-seam.md` ("Host-callables channel —
// chromeBindingsModule").
//
// Typed via an INLINE `import(...)` type (not a top-level import, which would
// break this file's ambient module declarations) — see the package's
// factory-context module (`src/factory-context/index.ts`) for the
// `ChromeHostBindings` shape.
declare module "virtual:zudo-doc-chrome-bindings" {
  export const chromeBindings: import("../factory-context/index.js").ChromeHostBindings;
}

// Ambient typing for the design-token-panel-config virtual module emitted by
// the routes plugin (`addVirtualModule("virtual:zudo-doc-design-token-panel-config",
// …)`, #2658). No on-disk source — materialised at build, either as a
// re-export of the host's `settings.designTokenPanelConfigModule` file or as
// a re-export of the package default (`@takazudo/zudo-doc/design-token-panel-config`)
// when the setting is absent. See `plugins/routes.ts` and this package's
// `design-token-panel-bootstrap.tsx` for the full contract.
//
// Typed via an inline `import(...)` type (not a top-level import, for the
// same ambient-module-declaration reason as `chromeBindings` above) — see
// `@takazudo/zdtp`'s `PanelConfig`.
declare module "virtual:zudo-doc-design-token-panel-config" {
  export const buildDesignTokenPanelConfig: (
    mode: "light" | "dark",
  ) => import("@takazudo/zdtp").PanelConfig;
}
