import { h, signal, Fragment } from "./takazudo-zfb-3.0.0/package/dist/zudo-react/index.js";
import { renderToString } from "./takazudo-zfb-3.0.0/package/dist/zudo-react/server.js";
const cases = {
  hreflang: () => h("link", { rel: "alternate", hreflang: "ja", href: "/ja/" }),
  ogProperty: () => h("meta", { property: "og:title", content: "x" }),
  scriptDefer: () => h("script", { src: "/a.js", defer: true }),
  scriptAsync: () => h("script", { type: "module", async: true, src: "/a.js" }),
  linkAs: () => h("link", { rel: "preload", as: "font", href: "/f.woff2", crossorigin: "" }),
  integrity: () => h("script", { src: "/a.js", integrity: "sha384-x" }),
  svgXmlns: () => h("svg", { xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 1 1" }),
  svgUseHref: () => h("svg", null, h("use", { href: "#i" })),
  svgFillOpacity: () => h("svg", null, h("path", { d: "M0 0", "fill-opacity": "0.5" })),
  svgStrokeDash: () => h("svg", null, h("path", { d: "M0 0", "stroke-dasharray": "2" })),
  svgTextAnchor: () => h("svg", null, h("text", { "text-anchor": "middle" }, "a")),
  svgAriaHidden: () => h("svg", { "aria-hidden": "true", class: "x" }),
  popover: () => h("div", { popover: "auto", id: "p" }),
  popovertarget: () => h("button", { popovertarget: "p" }, "x"),
  olStart: () => h("ol", { start: 3 }),
  inputList: () => h("input", { list: "d" }),
  optionLabel: () => h("option", { label: "x", value: "x" }),
  htmlLang: () => h("html", { lang: "en", "data-theme": "light" }),
  nonce: () => h("script", { nonce: "n" }),
  fetchpriority: () => h("img", { src: "a", alt: "", fetchpriority: "high" }),
  itemprop: () => h("span", { itemprop: "name" }),
  inputmode: () => h("input", { inputmode: "search" }),
  enterkeyhint: () => h("input", { enterkeyhint: "search" }),
  iframeFrameborder: () => h("iframe", { src: "x", frameborder: "0" }),
  svgPattern: () => h("svg", null, h("pattern", { id: "p" })),
  svgFilter: () => h("svg", null, h("filter", { id: "f" })),
  svgMarker: () => h("svg", null, h("marker", { id: "m" })),
  svgImage: () => h("svg", null, h("image", { href: "a.png" })),
  svgClipPathAttr: () => h("svg", null, h("g", { "clip-path": "url(#c)" })),
  svgStyleObj: () => h("svg", { style: { "vertical-align": "middle" } }),
  camelStyle: () => h("div", { style: { backgroundColor: "red" } }),
  classNameProp: () => h("div", { className: "x" }),
  onClick: () => h("button", { onClick: () => {} }),
  onClickNative: () => h("button", { "on:click": () => {} }, "x"),
  dangerously: () => h("div", { dangerouslySetInnerHTML: { __html: "<b>x</b>" } }),
  rawHtml: () => h("div", { rawHtml: "<b>x</b>" }),
  rawHtmlSvg: () => h("svg", { rawHtml: "<path d='M0 0'/>" }),
  tabIndexNum: () => h("div", { tabindex: 0 }),
  booleanAriaFalse: () => h("button", { "aria-expanded": false }, "x"),
  hiddenUntilFound: () => h("div", { hidden: "until-found" }),
  customEl: () => h("zudo-thing", { mode: "a" }),
  customElNum: () => h("zudo-thing", { count: 3 }),
  tableNoTbody: () => h("table", null, h("tr", null, h("td", null, "x"))),
  inputChecked: () => h("input", { type: "checkbox", checked: true }),
  valueSignal: () => h("input", { value: signal("x") }),
  textSignal: () => h("p", null, signal("x")),
  detailsOpen: () => h("details", { open: true }, h("summary", null, "s")),
  dialogOpen: () => h("dialog", { open: false }),
  asyncComp: () => h(async function A(){ return "x"; }, null),
  selectMultiple: () => h("select", { multiple: true }, h("option", { value: "a" }, "a")),
  textareaDefault: () => h("textarea", { defaultValue: "x" }),
  labelFor: () => h("label", { for: "x" }, "l"),
  htmlFor: () => h("label", { htmlFor: "x" }, "l"),
  metaCharset: () => h("meta", { charset: "utf-8" }),
  metaName: () => h("meta", { name: "viewport", content: "width=device-width" }),
  linkSizes: () => h("link", { rel: "icon", sizes: "32x32", type: "image/png", href: "/f.png" }),
  linkColor: () => h("link", { rel: "mask-icon", color: "#000", href: "/f.svg" }),
  imgWidthNum: () => h("img", { src: "a", alt: "", width: 10, height: 10 }),
  styleString: () => h("div", { style: "color:red" }),
  styleNum: () => h("div", { style: { "z-index": 3, "--x": 1 } }),
  kbd: () => h("kbd", null, "k"),
  searchTag: () => h("search", null, "x"),
  menuTag: () => h("menu", null, "x"),
  headerTag: () => h("hgroup", null, "x"),
};
for (const [k, fn] of Object.entries(cases)) {
  try { const out = renderToString(fn()); console.log("OK  ", k, JSON.stringify(out).slice(0, 110)); }
  catch (e) { console.log("FAIL", k, String(e.message).slice(0, 140)); }
}
