/**
 * close-stale-issues.test.ts
 *
 * Unit tests for:
 *   - scripts/migration-check/lib/parse-issue-signature.mjs (pure parser)
 *   - scripts/migration-check/close-stale-issues.mjs (core logic)
 *
 * Coverage:
 *   parseIssueSignature
 *     - Canonical body shape (table row) → correct signature extracted
 *     - Prose fallback shape → correct signature extracted
 *     - Body without signature line → null (logged for manual review)
 *     - Empty / non-string body → null
 *     - Whitespace variants in table row → handled
 *
 *   loadLiveSignatures
 *     - Signatures from batch files are collected into a Set
 *     - Non-batch files (batch-*-detailed.json) are excluded
 *     - Missing findingsDir returns empty Set (no crash)
 *
 *   buildCloseComment
 *     - Contains ISO timestamp and short SHA
 *     - Contains the exact template text from spec
 *
 *   closeStaleIssues
 *     - Closes issue whose signature is NOT in live set
 *     - Keeps issue whose signature IS in live set
 *     - dry-run: emits WOULD CLOSE lines, no gh mutations
 *     - dry-run: emits WOULD KEEP lines for live issues
 *     - Issues with unparseable body are skipped (not closed), logged for review
 *     - Idempotency — second run is a no-op when live set is unchanged
 *     - Empty findings dir → all open issues would be closed (signatures absent)
 *     - gh issue list failure → returns empty result, no crash
 *     - Already-closed issue → skipped (only open issues are fetched)
 */

import { mkdir, writeFile, rm } from "node:fs/promises";
import { tmpdir }               from "node:os";
import { join }                 from "node:path";
import { describe, it, expect } from "vitest";

import { parseIssueSignature }                         from "../lib/parse-issue-signature.mjs";
import { loadLiveSignatures, buildCloseComment, closeStaleIssues } from "../close-stale-issues.mjs";

// ── Fixtures ──────────────────────────────────────────────────────────────────

/**
 * Build an issue body in the exact format generated by raise-issues.mjs.
 * The **Signature** field is a Markdown table cell containing `cluster.signature`.
 */
function makeIssueBody(signature: string): string {
  return [
    "## Migration Regression: structural",
    "",
    "| Field | Value |",
    "| --- | --- |",
    "| **Category** | `structural` |",
    "| **Routes affected** | 3 |",
    `| **Signature** | \`${signature}\` |`,
    "| **Hash marker** | `abc12345` |",
    "| **Description** | DOM shape changed |",
  ].join("\n");
}

/**
 * Write a minimal findings directory containing one batch file.
 * Returns the absolute path to the findings directory.
 */
async function writeFindingsDir(
  baseDir: string,
  findings: object[],
): Promise<string> {
  const findingsDir = join(baseDir, "findings");
  await mkdir(findingsDir, { recursive: true });

  const batch = { batchId: "0000", routes: findings };
  await writeFile(join(findingsDir, "batch-0000.json"), JSON.stringify(batch, null, 2));

  return findingsDir;
}

/** Build a structural finding with the given DOM shape hash pair. */
function makeStructuralFinding(hashA: string, hashB: string, route = "/docs/page") {
  return {
    route,
    category:        "structural",
    subCategory:     null,
    signals:         { domShapeHashA: hashA, domShapeHashB: hashB },
    diffSummaryHash: null,
  };
}

// ── Unit: parseIssueSignature ─────────────────────────────────────────────────

describe("parseIssueSignature — canonical table row", () => {
  it("extracts signature from the standard Markdown table body", () => {
    const body = makeIssueBody("aaa111::bbb222");
    expect(parseIssueSignature(body)).toBe("aaa111::bbb222");
  });

  it("handles whitespace around pipes and backtick cell", () => {
    const body = "| **Signature** |  `my-sig::value`  |";
    expect(parseIssueSignature(body)).toBe("my-sig::value");
  });

  it("returns the full signature, not just a prefix", () => {
    const longSig = "a".repeat(40) + "::" + "b".repeat(40);
    const body    = makeIssueBody(longSig);
    expect(parseIssueSignature(body)).toBe(longSig);
  });
});

describe("parseIssueSignature — prose fallback", () => {
  it("extracts signature from **Signature**: `value` prose form", () => {
    const body = "**Signature**: `canonical-changed`";
    expect(parseIssueSignature(body)).toBe("canonical-changed");
  });

  it("prose form: allows whitespace between colon and backtick", () => {
    const body = "**Signature**:  `og-changed`";
    expect(parseIssueSignature(body)).toBe("og-changed");
  });
});

describe("parseIssueSignature — missing or malformed body", () => {
  it("returns null when body has no **Signature** line", () => {
    const body = "## Some issue\n\nNo signature here.";
    expect(parseIssueSignature(body)).toBeNull();
  });

  it("returns null for empty string", () => {
    expect(parseIssueSignature("")).toBeNull();
  });

  it("returns null for non-string input (null)", () => {
    // @ts-expect-error — intentional runtime type violation test
    expect(parseIssueSignature(null)).toBeNull();
  });

  it("returns null for non-string input (undefined)", () => {
    // @ts-expect-error — intentional runtime type violation test
    expect(parseIssueSignature(undefined)).toBeNull();
  });
});

// ── Unit: loadLiveSignatures ──────────────────────────────────────────────────

describe("loadLiveSignatures", () => {
  it("collects cluster signatures from batch files", async () => {
    const dir = join(tmpdir(), `cls-live-${Date.now()}`);
    const findingsDir = await writeFindingsDir(dir, [
      makeStructuralFinding("hashA1", "hashB1", "/docs/a"),
      makeStructuralFinding("hashA2", "hashB2", "/docs/b"),
    ]);

    const liveSet = await loadLiveSignatures(findingsDir);

    expect(liveSet.has("hashA1::hashB1")).toBe(true);
    expect(liveSet.has("hashA2::hashB2")).toBe(true);

    await rm(dir, { recursive: true, force: true }).catch(() => {});
  });

  it("returns an empty Set when findingsDir does not exist", async () => {
    const liveSet = await loadLiveSignatures("/tmp/__no-such-dir-cls-test__");
    expect(liveSet.size).toBe(0);
  });

  it("excludes batch-*-detailed.json files (only batch-NNNN.json)", async () => {
    const dir         = join(tmpdir(), `cls-exclude-${Date.now()}`);
    const findingsDir = join(dir, "findings");
    await mkdir(findingsDir, { recursive: true });

    // Write a summary file (should be included)
    const summary = { batchId: "0000", routes: [makeStructuralFinding("hA", "hB")] };
    await writeFile(join(findingsDir, "batch-0000.json"), JSON.stringify(summary));

    // Write a detailed file (must be ignored)
    const detailed = { batchId: "0000", routes: [makeStructuralFinding("hC", "hD")] };
    await writeFile(join(findingsDir, "batch-0000-detailed.json"), JSON.stringify(detailed));

    const liveSet = await loadLiveSignatures(findingsDir);

    expect(liveSet.has("hA::hB")).toBe(true);
    expect(liveSet.has("hC::hD")).toBe(false);

    await rm(dir, { recursive: true, force: true }).catch(() => {});
  });
});

// ── Unit: buildCloseComment ───────────────────────────────────────────────────

describe("buildCloseComment", () => {
  const isoTimestamp = "2026-04-30T12:00:00.000Z";
  const shortSha     = "abc1234";

  it("includes the ISO timestamp", () => {
    const comment = buildCloseComment({ isoTimestamp, shortSha });
    expect(comment).toContain(isoTimestamp);
  });

  it("includes the short SHA in backticks", () => {
    const comment = buildCloseComment({ isoTimestamp, shortSha });
    expect(comment).toContain(`\`${shortSha}\``);
  });

  it("references the script file name", () => {
    const comment = buildCloseComment({ isoTimestamp, shortSha });
    expect(comment).toContain("close-stale-issues.mjs");
  });

  it("mentions Phase B-N migration-parity work", () => {
    const comment = buildCloseComment({ isoTimestamp, shortSha });
    expect(comment).toContain("Phase B-N migration-parity work");
  });

  it("mentions /l-zfb-migration-check", () => {
    const comment = buildCloseComment({ isoTimestamp, shortSha });
    expect(comment).toContain("/l-zfb-migration-check");
  });
});

// ── Integration: closeStaleIssues ─────────────────────────────────────────────

describe("closeStaleIssues — closes stale issue", () => {
  it("closes an issue whose signature is not in the live set", async () => {
    const dir = join(tmpdir(), `cls-close-${Date.now()}`);
    const findingsDir = await writeFindingsDir(dir, [
      makeStructuralFinding("liveA", "liveB"),
    ]);

    // Issue whose signature is NOT in the live findings
    const ghCalls: string[][] = [];
    const mockGh = async (args: string[]) => {
      ghCalls.push(args);
      if (args[0] === "issue" && args[1] === "list") {
        return JSON.stringify([
          { number: 600, title: "[migration-regression:deadbeef] structural: foo", body: makeIssueBody("staleA::staleB") },
        ]);
      }
      return "";
    };

    const result = await closeStaleIssues({ findingsDir, _runGh: mockGh });

    expect(result.closed).toEqual(["600"]);
    expect(result.kept).toEqual([]);
    expect(result.skipped).toEqual([]);

    // gh issue comment + gh issue close must have been called
    const commentCall = ghCalls.find((a) => a[0] === "issue" && a[1] === "comment");
    expect(commentCall).toBeDefined();
    const closeCall = ghCalls.find((a) => a[0] === "issue" && a[1] === "close");
    expect(closeCall).toBeDefined();

    await rm(dir, { recursive: true, force: true }).catch(() => {});
  });

  it("close comment contains the script file name and run info", async () => {
    const dir = join(tmpdir(), `cls-comment-${Date.now()}`);
    const findingsDir = await writeFindingsDir(dir, [
      makeStructuralFinding("liveA", "liveB"),
    ]);

    const commentBodies: string[] = [];
    const mockGh = async (args: string[]) => {
      if (args[0] === "issue" && args[1] === "list") {
        return JSON.stringify([
          { number: 601, title: "[migration-regression:deadbeef] structural: foo", body: makeIssueBody("staleX::staleY") },
        ]);
      }
      if (args[0] === "issue" && args[1] === "comment") {
        const bodyIdx = args.indexOf("--body");
        if (bodyIdx >= 0) commentBodies.push(args[bodyIdx + 1]);
      }
      return "";
    };

    await closeStaleIssues({ findingsDir, _runGh: mockGh });

    expect(commentBodies).toHaveLength(1);
    expect(commentBodies[0]).toContain("close-stale-issues.mjs");
    expect(commentBodies[0]).toContain("Phase B-N migration-parity work");
  });
});

describe("closeStaleIssues — keeps live issue", () => {
  it("does NOT close an issue whose signature is in the live set", async () => {
    const dir = join(tmpdir(), `cls-keep-${Date.now()}`);
    const findingsDir = await writeFindingsDir(dir, [
      makeStructuralFinding("liveA", "liveB"),
    ]);

    const ghCalls: string[][] = [];
    const mockGh = async (args: string[]) => {
      ghCalls.push(args);
      if (args[0] === "issue" && args[1] === "list") {
        // Issue with the SAME signature as the live finding
        return JSON.stringify([
          { number: 602, title: "[migration-regression:abcd1234] structural: foo", body: makeIssueBody("liveA::liveB") },
        ]);
      }
      return "";
    };

    const result = await closeStaleIssues({ findingsDir, _runGh: mockGh });

    expect(result.kept).toEqual(["602"]);
    expect(result.closed).toEqual([]);
    expect(result.skipped).toEqual([]);

    const closeCall = ghCalls.find((a) => a[0] === "issue" && a[1] === "close");
    expect(closeCall).toBeUndefined();

    await rm(dir, { recursive: true, force: true }).catch(() => {});
  });
});

describe("closeStaleIssues — dry-run mode", () => {
  it("dry-run emits no gh mutation calls", async () => {
    const dir = join(tmpdir(), `cls-dryrun-${Date.now()}`);
    const findingsDir = await writeFindingsDir(dir, [
      makeStructuralFinding("liveA", "liveB"),
    ]);

    const ghCalls: string[][] = [];
    const mockGh = async (args: string[]) => {
      ghCalls.push(args);
      if (args[0] === "issue" && args[1] === "list") {
        return JSON.stringify([
          { number: 610, title: "[migration-regression:aaa11111] structural: foo", body: makeIssueBody("staleX::staleY") },
          { number: 611, title: "[migration-regression:bbb22222] structural: bar", body: makeIssueBody("liveA::liveB") },
        ]);
      }
      return "";
    };

    const result = await closeStaleIssues({ findingsDir, dryRun: true, _runGh: mockGh });

    // Should classify correctly
    expect(result.closed).toEqual(["610"]);
    expect(result.kept).toEqual(["611"]);

    // No mutation calls (comment or close)
    const commentCall = ghCalls.find((a) => a[0] === "issue" && a[1] === "comment");
    const closeCall   = ghCalls.find((a) => a[0] === "issue" && a[1] === "close");
    expect(commentCall).toBeUndefined();
    expect(closeCall).toBeUndefined();

    await rm(dir, { recursive: true, force: true }).catch(() => {});
  });
});

describe("closeStaleIssues — unparseable body", () => {
  it("skips issues with no parseable **Signature** in body", async () => {
    const dir = join(tmpdir(), `cls-noparse-${Date.now()}`);
    const findingsDir = await writeFindingsDir(dir, [
      makeStructuralFinding("liveA", "liveB"),
    ]);

    const ghCalls: string[][] = [];
    const mockGh = async (args: string[]) => {
      ghCalls.push(args);
      if (args[0] === "issue" && args[1] === "list") {
        return JSON.stringify([
          { number: 620, title: "[migration-regression:abcdef01] structural: no-body", body: "## Something\n\nNo signature row here." },
        ]);
      }
      return "";
    };

    const result = await closeStaleIssues({ findingsDir, dryRun: true, _runGh: mockGh });

    // Issue with missing body signature must be skipped, not closed
    expect(result.skipped).toEqual(["620"]);
    expect(result.closed).toEqual([]);
    expect(result.kept).toEqual([]);

    await rm(dir, { recursive: true, force: true }).catch(() => {});
  });
});

describe("closeStaleIssues — idempotency", () => {
  it("second dry-run is a no-op when all issue signatures are in the live set", async () => {
    const dir = join(tmpdir(), `cls-idem-${Date.now()}`);
    // Live set = [liveA::liveB]
    const findingsDir = await writeFindingsDir(dir, [
      makeStructuralFinding("liveA", "liveB"),
    ]);

    const mockGh = async (args: string[]) => {
      if (args[0] === "issue" && args[1] === "list") {
        // Only one open issue, signature IS in live set
        return JSON.stringify([
          { number: 630, title: "[migration-regression:abcdef01] structural: live", body: makeIssueBody("liveA::liveB") },
        ]);
      }
      return "";
    };

    const run1 = await closeStaleIssues({ findingsDir, dryRun: true, _runGh: mockGh });
    const run2 = await closeStaleIssues({ findingsDir, dryRun: true, _runGh: mockGh });

    // Both runs: nothing to close
    expect(run1.closed).toEqual([]);
    expect(run2.closed).toEqual([]);
    expect(run1.kept).toEqual(["630"]);
    expect(run2.kept).toEqual(["630"]);

    await rm(dir, { recursive: true, force: true }).catch(() => {});
  });

  it("second run after live close finds no open issues (already closed)", async () => {
    const dir = join(tmpdir(), `cls-idem2-${Date.now()}`);
    const findingsDir = await writeFindingsDir(dir, []);  // empty live set

    let openIssues = [
      { number: 640, title: "[migration-regression:abcdef01] structural: stale", body: makeIssueBody("staleA::staleB") },
    ];

    const mockGh = async (args: string[]) => {
      if (args[0] === "issue" && args[1] === "list") {
        // Simulate that after closure the issue is no longer open
        return JSON.stringify(openIssues);
      }
      if (args[0] === "issue" && args[1] === "close") {
        openIssues = [];  // issue is now closed
      }
      return "";
    };

    const run1 = await closeStaleIssues({ findingsDir, _runGh: mockGh });
    expect(run1.closed).toEqual(["640"]);

    const run2 = await closeStaleIssues({ findingsDir, _runGh: mockGh });
    expect(run2.closed).toEqual([]);   // no-op: issue gone from open list

    await rm(dir, { recursive: true, force: true }).catch(() => {});
  });
});

describe("closeStaleIssues — gh list failure", () => {
  it("returns empty result and does not crash when gh issue list fails", async () => {
    const dir = join(tmpdir(), `cls-ghfail-${Date.now()}`);
    const findingsDir = await writeFindingsDir(dir, [
      makeStructuralFinding("liveA", "liveB"),
    ]);

    const mockGh = async (args: string[]) => {
      if (args[0] === "issue" && args[1] === "list") {
        throw new Error("gh: network error");
      }
      return "";
    };

    const result = await closeStaleIssues({ findingsDir, _runGh: mockGh });

    expect(result.closed).toEqual([]);
    expect(result.kept).toEqual([]);
    expect(result.skipped).toEqual([]);

    await rm(dir, { recursive: true, force: true }).catch(() => {});
  });
});
