// sidebar-utils — parameterized `buildSidebarForSection` pure function
// (epic #2344, S5).
//
// The host's `src/utils/sidebar.ts` previously imported `sidebars` from
// `@/config/sidebars` at module scope. This module receives the sidebars
// config, nav tree, and helpers as arguments so the logic lives in the
// package while the host stub keeps the singleton imports.
//
// Pure functions — no node builtins, no `@/` host alias imports.

// ---------------------------------------------------------------------------
// Sidebar item types (mirrors src/config/sidebars.ts)
// ---------------------------------------------------------------------------

export interface SidebarLink {
  type: "link";
  label: string;
  href: string;
}

export interface SidebarDoc {
  type: "doc";
  /** Doc slug, e.g. "getting-started/introduction" */
  id: string;
  /** Override the doc's title in sidebar */
  label?: string;
}

export interface SidebarCategory {
  type: "category";
  label: string;
  items: SidebarItem[];
  collapsed?: boolean;
  sortOrder?: "asc" | "desc";
}

export interface SidebarAutogenerated {
  type: "autogenerated";
  dirName?: string;
}

/**
 * A sidebar item — string shorthand is equivalent to `{ type: "doc", id: slug }`.
 */
export type SidebarItem =
  | SidebarDoc
  | SidebarLink
  | SidebarCategory
  | SidebarAutogenerated
  | string;

/** An explicit editorial tree with an optional local view of a category's children. */
export interface SidebarDefinition {
  items: SidebarItem[];
  /** Resolved occurrence indexes from the forest to a category (not URL segments). */
  initialPath?: number[];
  /** Share across sections using the same editorial tree. Locale/version are added by chrome. */
  contextId?: string;
}

/** Sidebar config keyed by section (categoryMatch value). */
export type SidebarsConfig = {
  [sectionKey: string]: SidebarItem[] | SidebarDefinition | undefined;
};

// ---------------------------------------------------------------------------
// Nav node type
// ---------------------------------------------------------------------------

export type { SidebarNavNode, SidebarNavigationContext } from "../sidebar/types.js";
import type { SidebarNavNode, SidebarNavigationContext } from "../sidebar/types.js";

// ---------------------------------------------------------------------------
// CategoryMeta type
// ---------------------------------------------------------------------------

/** Category metadata shape (mirrors host's CategoryMeta). */
export interface SidebarCategoryMeta {
  label?: string;
  position?: number;
  collapsed?: boolean;
}

// ---------------------------------------------------------------------------
// Helpers (used by buildSidebarForSection)
// ---------------------------------------------------------------------------

/** Find a node by slug in a nav tree (depth-first). */
function findNode(tree: SidebarNavNode[], slug: string): SidebarNavNode | undefined {
  for (const node of tree) {
    if (node.slug === slug) return node;
    if (node.children.length > 0) {
      const found = findNode(node.children, slug);
      if (found) return found;
    }
  }
  return undefined;
}

function resolveItems(
  items: SidebarItem[],
  tree: SidebarNavNode[],
  lang: string,
): SidebarNavNode[] {
  return items.flatMap((item) => resolveItem(item, tree, lang));
}

function resolveItem(
  item: SidebarItem,
  tree: SidebarNavNode[],
  lang: string,
): SidebarNavNode[] {
  if (typeof item === "string") {
    const node = findNode(tree, item);
    return node ? [{ ...node, children: [] }] : [];
  }

  switch (item.type) {
    case "doc": {
      const node = findNode(tree, item.id);
      if (!node) return [];
      return [{ ...node, children: [], ...(item.label ? { label: item.label } : {}) }];
    }
    case "link": {
      return [
        {
          slug: `__link__${item.href}`,
          label: item.label,
          href: item.href,
          position: 0,
          hasPage: false,
          children: [],
        },
      ];
    }
    case "category": {
      const children = resolveItems(item.items, tree, lang);
      if (item.sortOrder === "desc") {
        children.reverse();
      }
      return [
        {
          slug: `__category__${item.label}`,
          label: item.label,
          position: 0,
          hasPage: false,
          href: undefined,
          children,
          sortOrder: item.sortOrder,
          collapsed: item.collapsed,
        },
      ];
    }
    case "autogenerated": {
      if (item.dirName) {
        const node = findNode(tree, item.dirName);
        return node ? node.children : [];
      }
      return tree;
    }
    default: {
      const _exhaustive: never = item;
      throw new Error(`Unhandled sidebar item type: ${JSON.stringify(_exhaustive)}`);
    }
  }
}

// ---------------------------------------------------------------------------
// Parameterized nav subtree filter (replaces the `getNavSubtree` import)
// ---------------------------------------------------------------------------

/**
 * Filter top-level nav nodes by categoryMatch. Accepts an explicit prefix set
 * so the function does not need to re-read `headerNav`.
 */
function filterByCategory(
  tree: SidebarNavNode[],
  categoryMatch: string | undefined,
  explicitPrefixes: string[],
): SidebarNavNode[] {
  if (!categoryMatch) return tree;

  if (categoryMatch === "!") {
    return tree.filter(
      (node) => !explicitPrefixes.some((prefix) => node.slug.startsWith(prefix)),
    );
  }

  return tree.filter((node) => node.slug.startsWith(categoryMatch));
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Build sidebar nodes for a given nav section.
 *
 * If sidebar config exists for this section, use it. Otherwise fall back to
 * the auto-generated tree filtered to the section's categoryMatch.
 *
 * Parameterized version of the host's `buildSidebarForSection` from
 * `src/utils/sidebar.ts` — receives `sidebars`, `buildNavTree`, and
 * `explicitCategoryPrefixes` as arguments instead of importing from
 * `@/config/sidebars`, `@/utils/docs`, `@/utils/nav-scope`.
 *
 * `explicitCategoryPrefixes` is the pre-computed list of non-`"!"` categoryMatch
 * values from headerNav, used for the `"!"` fallback category filter.
 */
export function buildSidebarForSection(
  docs: unknown[],
  lang: string,
  categoryMatch: string | undefined,
  categoryMeta: Map<string, SidebarCategoryMeta> | undefined,
  sidebars: SidebarsConfig,
  buildNavTree: (
    docs: unknown[],
    lang: string,
    categoryMeta?: Map<string, SidebarCategoryMeta>,
  ) => SidebarNavNode[],
  explicitCategoryPrefixes: string[],
): SidebarNavNode[] {
  const tree = buildNavTree(docs, lang, categoryMeta);

  const sectionKey = categoryMatch ?? "default";
  const config = sidebars[sectionKey];

  if (!config || (Array.isArray(config) ? config.length === 0 : config.items.length === 0)) {
    return filterByCategory(tree, categoryMatch, explicitCategoryPrefixes);
  }

  if (Array.isArray(config)) return resolveItems(config, tree, lang);
  let nodes = resolveItems(config.items, tree, lang);
  for (const index of config.initialPath ?? []) {
    if (!Number.isInteger(index) || index < 0 || !nodes[index]) throw new Error(`Invalid sidebar initialPath for ${sectionKey}`);
    nodes = nodes[index]!.children;
  }
  return nodes;
}

/** Builder-owned provenance keeps omitted autogenerated roots and duplicate links distinct. */
export function buildSidebarNavigation(
  ...args: Parameters<typeof buildSidebarForSection>
): { nodes: SidebarNavNode[]; navigation: SidebarNavigationContext } {
  const [docs, lang, categoryMatch, meta, sidebars, buildTree, prefixes] = args;
  const initialExpansion: Record<string, "collapsed" | "expanded"> = {};
  for (const entry of docs) {
    const doc = entry as { slug?: string; data?: { slug?: string; sidebar_initial_expansion?: unknown } };
    const value = doc.data?.sidebar_initial_expansion;
    if (typeof doc.slug === "string" && (value === "collapsed" || value === "expanded")) {
      const slug = doc.data?.slug ?? (doc.slug === "index" ? "" : doc.slug.replace(/\/index$/, ""));
      initialExpansion[slug] = value;
    }
  }
  const tree = buildTree(docs, lang, meta);
  const config = sidebars[categoryMatch ?? "default"];
  const definition = config && !Array.isArray(config) ? config : undefined;
  const items = Array.isArray(config) ? config : definition?.items;
  const parents: Record<string, string | null> = {};
  function identify(nodes: SidebarNavNode[], prefix: string, parent: string | null): SidebarNavNode[] {
    return nodes.map((node, index) => {
      const occurrenceId = `${prefix}/${index}`;
      parents[occurrenceId] = parent;
      return { ...node, occurrenceId, children: identify(node.children, occurrenceId, occurrenceId) };
    });
  }
  const automatic = identify(tree, "auto", null);
  let roots: SidebarNavNode[];
  let nodes: SidebarNavNode[];
  if (!items?.length) {
    roots = automatic;
    nodes = filterByCategory(roots, categoryMatch, prefixes);
  } else if (items.length === 1 && typeof items[0] !== "string" && items[0]?.type === "autogenerated") {
    roots = automatic;
    nodes = items[0].dirName ? findNode(roots, items[0].dirName)?.children ?? [] : roots;
  } else {
    // Resolve canonical and visible children together. An autogenerated node may
    // be absent from the visible forest but remains an actual parent occurrence.
    function resolve(entries: SidebarItem[], prefix: string, parent: string | null): { canonical: SidebarNavNode[]; visible: SidebarNavNode[] } {
      const canonical: SidebarNavNode[] = [];
      const visible: SidebarNavNode[] = [];
      entries.forEach((item, index) => {
        const id = `${prefix}/${index}`;
        if (typeof item !== "string" && item.type === "category") {
          const children = resolve(item.items, id, id);
          if (item.sortOrder === "desc") { children.canonical.reverse(); children.visible.reverse(); }
          const node: SidebarNavNode = { occurrenceId: id, slug: `__category__${item.label}`, label: item.label, position: 0, hasPage: false, collapsed: item.collapsed, sortOrder: item.sortOrder, children: children.canonical };
          parents[id] = parent;
          canonical.push(node);
          visible.push({ ...node, children: children.visible });
        } else if (typeof item !== "string" && item.type === "autogenerated" && item.dirName) {
          const source = findNode(tree, item.dirName);
          if (source) {
            const identified = identify([source], id, parent)[0]!;
            canonical.push(identified);
            visible.push(...identified.children);
          }
        } else {
          const resolved = identify(resolveItem(item, tree, lang), id, parent);
          canonical.push(...resolved);
          visible.push(...resolved);
        }
      });
      return { canonical, visible };
    }
    for (const id of Object.keys(parents)) delete parents[id];
    const result = resolve(items, "custom", null);
    roots = result.canonical;
    nodes = result.visible;
  }
  let localParentId: string | undefined;
  for (const index of definition?.initialPath ?? []) {
    const node = nodes[index];
    if (!Number.isInteger(index) || index < 0 || !node) throw new Error(`Invalid sidebar initialPath for ${categoryMatch ?? "default"}`);
    localParentId = node.occurrenceId;
    nodes = node.children;
  }
  // Topology fingerprint invalidates stored paths after authored order/content changes.
  // Includes hrefs so base paths and independent document contexts cannot collide.
  let hash = 2166136261;
  const serialized = JSON.stringify(Object.keys(initialExpansion).length ? [roots, initialExpansion] : roots);
  for (let i = 0; i < serialized.length; i++) hash = Math.imul(hash ^ serialized.charCodeAt(i), 16777619);
  const kind = !items?.length || (items.length === 1 && typeof items[0] !== "string" && items[0]?.type === "autogenerated") ? "automatic" : definition?.contextId ?? categoryMatch ?? "default";
  return { nodes, navigation: { id: `${lang}:${kind}:${hash >>> 0}`, roots, parents, ...(Object.keys(initialExpansion).length ? { initialExpansion } : {}), ...(localParentId ? { localParentId } : {}) } };
}

export { sidebarInitialExpansion, sidebarBaselineOpen, SIDEBAR_FOREST_SCOPE, indexSidebarOccurrences, sidebarScopeNodes, broaderSidebarScope, reconcileSidebarScope } from "./scope.js";
