// sidebar-utils — parameterized `buildSidebarForSection` pure function
// (epic #2344, S5).
//
// The host's `src/utils/sidebar.ts` previously imported `sidebars` from
// `@/config/sidebars` at module scope. This module receives the sidebars
// config, nav tree, and helpers as arguments so the logic lives in the
// package while the host stub keeps the singleton imports.
//
// Pure functions — no node builtins, no `@/` host alias imports.

// ---------------------------------------------------------------------------
// Sidebar item types (mirrors src/config/sidebars.ts)
// ---------------------------------------------------------------------------

export interface SidebarLink {
  type: "link";
  label: string;
  href: string;
}

export interface SidebarDoc {
  type: "doc";
  /** Doc slug, e.g. "getting-started/introduction" */
  id: string;
  /** Override the doc's title in sidebar */
  label?: string;
}

export interface SidebarCategory {
  type: "category";
  label: string;
  items: SidebarItem[];
  collapsed?: boolean;
  sortOrder?: "asc" | "desc";
}

export interface SidebarAutogenerated {
  type: "autogenerated";
  dirName?: string;
}

/**
 * A sidebar item — string shorthand is equivalent to `{ type: "doc", id: slug }`.
 */
export type SidebarItem =
  | SidebarDoc
  | SidebarLink
  | SidebarCategory
  | SidebarAutogenerated
  | string;

/** Sidebar config keyed by section (categoryMatch value). */
export type SidebarsConfig = {
  [sectionKey: string]: SidebarItem[] | undefined;
};

// ---------------------------------------------------------------------------
// Nav node type
// ---------------------------------------------------------------------------

/** Minimal nav node shape required by sidebar-utils functions. */
export interface SidebarNavNode {
  slug: string;
  label: string;
  description?: string;
  position: number;
  href?: string;
  hasPage: boolean;
  children: SidebarNavNode[];
  sortOrder?: "asc" | "desc";
  collapsed?: boolean;
}

// ---------------------------------------------------------------------------
// CategoryMeta type
// ---------------------------------------------------------------------------

/** Category metadata shape (mirrors host's CategoryMeta). */
export interface SidebarCategoryMeta {
  label?: string;
  position?: number;
  collapsed?: boolean;
}

// ---------------------------------------------------------------------------
// Helpers (used by buildSidebarForSection)
// ---------------------------------------------------------------------------

/** Find a node by slug in a nav tree (depth-first). */
function findNode(tree: SidebarNavNode[], slug: string): SidebarNavNode | undefined {
  for (const node of tree) {
    if (node.slug === slug) return node;
    if (node.children.length > 0) {
      const found = findNode(node.children, slug);
      if (found) return found;
    }
  }
  return undefined;
}

function resolveItems(
  items: SidebarItem[],
  tree: SidebarNavNode[],
  lang: string,
): SidebarNavNode[] {
  return items.flatMap((item) => resolveItem(item, tree, lang));
}

function resolveItem(
  item: SidebarItem,
  tree: SidebarNavNode[],
  lang: string,
): SidebarNavNode[] {
  if (typeof item === "string") {
    const node = findNode(tree, item);
    return node ? [{ ...node, children: [] }] : [];
  }

  switch (item.type) {
    case "doc": {
      const node = findNode(tree, item.id);
      if (!node) return [];
      return [{ ...node, children: [], ...(item.label ? { label: item.label } : {}) }];
    }
    case "link": {
      return [
        {
          slug: `__link__${item.href}`,
          label: item.label,
          href: item.href,
          position: 0,
          hasPage: false,
          children: [],
        },
      ];
    }
    case "category": {
      const children = resolveItems(item.items, tree, lang);
      if (item.sortOrder === "desc") {
        children.reverse();
      }
      return [
        {
          slug: `__category__${item.label}`,
          label: item.label,
          position: 0,
          hasPage: false,
          href: undefined,
          children,
          sortOrder: item.sortOrder,
          collapsed: item.collapsed,
        },
      ];
    }
    case "autogenerated": {
      if (item.dirName) {
        const node = findNode(tree, item.dirName);
        return node ? node.children : [];
      }
      return tree;
    }
    default: {
      const _exhaustive: never = item;
      throw new Error(`Unhandled sidebar item type: ${JSON.stringify(_exhaustive)}`);
    }
  }
}

// ---------------------------------------------------------------------------
// Parameterized nav subtree filter (replaces the `getNavSubtree` import)
// ---------------------------------------------------------------------------

/**
 * Filter top-level nav nodes by categoryMatch. Accepts an explicit prefix set
 * so the function does not need to re-read `headerNav`.
 */
function filterByCategory(
  tree: SidebarNavNode[],
  categoryMatch: string | undefined,
  explicitPrefixes: string[],
): SidebarNavNode[] {
  if (!categoryMatch) return tree;

  if (categoryMatch === "!") {
    return tree.filter(
      (node) => !explicitPrefixes.some((prefix) => node.slug.startsWith(prefix)),
    );
  }

  return tree.filter((node) => node.slug.startsWith(categoryMatch));
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Build sidebar nodes for a given nav section.
 *
 * If sidebar config exists for this section, use it. Otherwise fall back to
 * the auto-generated tree filtered to the section's categoryMatch.
 *
 * Parameterized version of the host's `buildSidebarForSection` from
 * `src/utils/sidebar.ts` — receives `sidebars`, `buildNavTree`, and
 * `explicitCategoryPrefixes` as arguments instead of importing from
 * `@/config/sidebars`, `@/utils/docs`, `@/utils/nav-scope`.
 *
 * `explicitCategoryPrefixes` is the pre-computed list of non-`"!"` categoryMatch
 * values from headerNav, used for the `"!"` fallback category filter.
 */
export function buildSidebarForSection(
  docs: unknown[],
  lang: string,
  categoryMatch: string | undefined,
  categoryMeta: Map<string, SidebarCategoryMeta> | undefined,
  sidebars: SidebarsConfig,
  buildNavTree: (
    docs: unknown[],
    lang: string,
    categoryMeta?: Map<string, SidebarCategoryMeta>,
  ) => SidebarNavNode[],
  explicitCategoryPrefixes: string[],
): SidebarNavNode[] {
  const tree = buildNavTree(docs, lang, categoryMeta);

  const sectionKey = categoryMatch ?? "default";
  const config = sidebars[sectionKey];

  if (!config || config.length === 0) {
    return filterByCategory(tree, categoryMatch, explicitCategoryPrefixes);
  }

  return resolveItems(config, tree, lang);
}
