import { describe, expect, it } from "vitest";
import { buildSidebarForSection, buildSidebarNavigation, broaderSidebarScope, indexSidebarOccurrences, reconcileSidebarScope, sidebarScopeNodes, SIDEBAR_FOREST_SCOPE, type SidebarsConfig, type SidebarNavNode } from "../index.js";

const leaf = (slug: string, children: SidebarNavNode[] = []): SidebarNavNode => ({ slug, label: slug, href: `/docs/${slug}`, position: 0, hasPage: true, children });
const tree = [leaf("utility", [leaf("utility/background"), leaf("utility/border")]), leaf("other", [leaf("other/page")])];
const build = (config: SidebarsConfig = {}) => buildSidebarNavigation([], "en", "utility", undefined, config, () => tree, ["utility"]);

describe("broader sidebar editorial provenance", () => {
  it("keeps legacy roots, order and collapse defaults, and broadens one actual level", () => {
    const config: SidebarsConfig = { utility: [{ type: "category", label: "Utility reference", collapsed: true, items: [{ type: "category", label: "Surfaces & borders", items: ["utility/background", "utility/border"] }] }] };
    const { nodes, navigation } = build(config);
    expect(nodes[0]?.collapsed).toBe(true);
    expect(buildSidebarForSection([], "en", "utility", undefined, config, () => tree, [])).toEqual(nodes.map(({ occurrenceId: _id, ...node }) => ({ ...node, children: node.children.map(({ occurrenceId: _child, ...child }) => ({ ...child, children: child.children.map(({ occurrenceId: _leaf, ...last }) => last) })) })));
    const group = nodes[0]!.children[0]!;
    const background = group.children[0]!;
    expect(navigation.parents[background.occurrenceId!]).toBe(group.occurrenceId);
    expect(broaderSidebarScope(navigation, nodes, group.occurrenceId!)).toBe(nodes[0]!.occurrenceId);
    expect(broaderSidebarScope(navigation, nodes, null)).toBeNull();
  });

  it("uses explicit local configuration with a non-URL editorial parent", () => {
    const config: SidebarsConfig = { utility: { items: [{ type: "category", label: "Utility reference", items: [{ type: "category", label: "Surfaces & borders", items: ["utility/background", "utility/border"] }] }], initialPath: [0, 0] } };
    const { nodes, navigation } = build(config);
    expect(nodes.map((n) => n.slug)).toEqual(["utility/background", "utility/border"]);
    const parent = broaderSidebarScope(navigation, nodes, null)!;
    expect(sidebarScopeNodes(navigation, nodes, parent)[0]?.label).toBe("Surfaces & borders");
    const grandparent = broaderSidebarScope(navigation, nodes, parent)!;
    expect(sidebarScopeNodes(navigation, nodes, grandparent)[0]?.label).toBe("Utility reference");
    expect(sidebarScopeNodes(navigation, nodes, null)).toBe(nodes);
  });

  it("retains an autogenerated root omitted from the configured view", () => {
    const { nodes, navigation } = build({ utility: [{ type: "autogenerated", dirName: "utility" }] });
    expect(nodes.map((node) => node.slug)).toEqual(["utility/background", "utility/border"]);
    const parent = broaderSidebarScope(navigation, nodes, null)!;
    expect(sidebarScopeNodes(navigation, nodes, parent)[0]?.slug).toBe("utility");
    expect(broaderSidebarScope(navigation, nodes, parent)).toBe(SIDEBAR_FOREST_SCOPE);
  });

  it("preserves authored ancestry around an autogenerated source", () => {
    const { nodes, navigation } = build({ utility: [{ type: "category", label: "Editorial", items: [{ type: "autogenerated", dirName: "utility" }] }] });
    const child = nodes[0]!.children[0]!;
    const parent = navigation.parents[child.occurrenceId!]!;
    expect(indexSidebarOccurrences(navigation.roots).get(parent)?.slug).toBe("utility");
    expect(navigation.parents[parent]).toBe(nodes[0]!.occurrenceId);
  });

  it("does not collapse duplicate labels or links and stops at a custom forest", () => {
    const { nodes, navigation } = build({ utility: [{ type: "category", label: "Same", items: ["utility/background"] }, { type: "category", label: "Same", items: ["utility/background"] }] });
    const index = indexSidebarOccurrences(navigation.roots);
    expect(index.size).toBe(4);
    expect(nodes[0]!.children[0]!.occurrenceId).not.toBe(nodes[1]!.children[0]!.occurrenceId);
    expect(broaderSidebarScope(navigation, nodes, null)).toBeNull();
    expect(sidebarScopeNodes(navigation, nodes, null)).toEqual(nodes);
  });

  it("widens to the nearest common ancestor, rejects stale scopes and resets unknown pages", () => {
    const { nodes, navigation } = build();
    const root = nodes[0]!;
    const child = root.children[0]!;
    expect(reconcileSidebarScope(navigation, nodes, root.occurrenceId!, "utility/border")).toBe(root.occurrenceId);
    expect(reconcileSidebarScope(navigation, nodes, child.occurrenceId!, "utility/border")).toBe(root.occurrenceId);
    expect(reconcileSidebarScope(navigation, nodes, root.occurrenceId!, "other/page")).toBe(SIDEBAR_FOREST_SCOPE);
    expect(reconcileSidebarScope(navigation, nodes, "stale", "utility/background")).toBeNull();
    expect(reconcileSidebarScope(navigation, nodes, root.occurrenceId!, "independent/page")).toBeNull();
  });

  it("handles twelve levels without a depth cap and changes context when topology changes", () => {
    let deep = leaf("leaf");
    for (let i = 12; i > 0; i--) deep = leaf(`level-${i}`, [deep]);
    const result = buildSidebarNavigation([], "en", undefined, undefined, {}, () => [deep], []);
    expect(indexSidebarOccurrences(result.navigation.roots).size).toBe(13);
    const leafId = [...indexSidebarOccurrences(result.navigation.roots)].find(([, node]) => node.slug === "leaf")![0];
    let scope: string | null = leafId;
    let count = 0;
    while ((scope = broaderSidebarScope(result.navigation, result.nodes, scope)) !== null) count++;
    expect(count).toBe(13);
    const changed = buildSidebarNavigation([], "ja", undefined, undefined, {}, () => [deep], []);
    expect(changed.navigation.id).not.toBe(result.navigation.id);
  });
});


it("keeps the explicit enclosing group for a mixed authored/autogenerated local forest", () => {
  const { nodes, navigation } = build({ utility: {
    items: [{ type: "category", label: "Editorial", items: ["other/page", { type: "autogenerated", dirName: "utility" }] }],
    initialPath: [0],
  } });
  const parent = broaderSidebarScope(navigation, nodes, null)!;
  expect(sidebarScopeNodes(navigation, nodes, parent)[0]?.label).toBe("Editorial");
  expect(sidebarScopeNodes(navigation, nodes, null).map((node) => node.slug)).toEqual(["other/page", "utility/background", "utility/border"]);
});


it("rejects invalid explicit paths rather than fabricating an enclosing group", () => {
  const config = { utility: { items: ["utility/background"], initialPath: [4] } };
  expect(() => build(config)).toThrow("Invalid sidebar initialPath");
  expect(() => buildSidebarForSection([], "en", "utility", undefined, config, () => tree, [])).toThrow("Invalid sidebar initialPath");
});


it("widens to include the canonical root-index page with an empty slug", () => {
  const { nodes, navigation } = buildSidebarNavigation([], "en", undefined, undefined, {}, () => [leaf(""), ...tree], []);
  const selected = nodes[1]!.occurrenceId!;
  expect(reconcileSidebarScope(navigation, nodes, selected, undefined)).toBe(selected);
  expect(reconcileSidebarScope(navigation, nodes, selected, "")).toBe(SIDEBAR_FOREST_SCOPE);
});
