/**
 * Sidebar configuration file.
 *
 * Items can be:
 * - "autogenerated" — auto-scan a directory (default behavior)
 * - doc references with optional overrides
 * - external links
 * - category groupings
 *
 * If this file exports an empty object or the key for a section is not found,
 * the sidebar falls back to filesystem-based auto-generation.
 */

import type { SidebarsConfig } from "@takazudo/zudo-doc/sidebar-utils";
export type { SidebarLink, SidebarDoc, SidebarCategory, SidebarAutogenerated, SidebarItem, SidebarDefinition, SidebarsConfig } from "@takazudo/zudo-doc/sidebar-utils";

/**
 * Sidebar configuration.
 * Keys correspond to headerNav categoryMatch values.
 * If a section has no config here, it uses auto-generated filesystem sidebar.
 */
const sidebars: SidebarsConfig = {
  // Example:
  // "!": [
  //   { type: "autogenerated" },
  //   { type: "link", label: "GitHub", href: "https://github.com/..." },
  // ],
};

export default sidebars;
