/**
 * Sidebar configuration file.
 *
 * Items can be:
 * - "autogenerated" — auto-scan a directory (default behavior)
 * - doc references with optional overrides
 * - external links
 * - category groupings
 *
 * If this file exports an empty object or the key for a section is not found,
 * the sidebar falls back to filesystem-based auto-generation.
 */

export interface SidebarLink {
  type: "link";
  label: string;
  href: string;
}

export interface SidebarDoc {
  type: "doc";
  id: string; // doc slug, e.g. "getting-started/introduction"
  label?: string; // override the doc's title in sidebar
}

export interface SidebarCategory {
  type: "category";
  label: string;
  items: SidebarItem[];
  collapsed?: boolean;
  sortOrder?: "asc" | "desc";
}

export interface SidebarAutogenerated {
  type: "autogenerated";
  dirName?: string; // subdirectory to scan (optional)
}

export type SidebarItem =
  | SidebarDoc
  | SidebarLink
  | SidebarCategory
  | SidebarAutogenerated
  | string;

// String shorthand: "getting-started/introduction" is equivalent to
// { type: "doc", id: "getting-started/introduction" }

export interface SidebarsConfig {
  [sectionKey: string]: SidebarItem[] | undefined;
}

/**
 * Sidebar configuration.
 * Keys correspond to headerNav categoryMatch values.
 * If a section has no config here, it uses auto-generated filesystem sidebar.
 */
const sidebars: SidebarsConfig = {
  // Example:
  // "!": [
  //   { type: "autogenerated" },
  //   { type: "link", label: "GitHub", href: "https://github.com/..." },
  // ],
};

export default sidebars;
