import sidebars from "@/config/sidebars";
import type { SidebarItem } from "@/config/sidebars";
import type { NavNode, CategoryMeta } from "@/utils/docs";
import { buildNavTree, findNode } from "@/utils/docs";
import { getNavSubtree } from "@/utils/nav-scope";
import type { Locale } from "@/config/i18n";
import type { DocsEntry } from "@/types/docs-entry";

/**
 * Build sidebar nodes for a given nav section.
 * If sidebar config exists for this section, use it.
 * Otherwise fall back to auto-generated tree.
 */
export function buildSidebarForSection(
  docs: DocsEntry[],
  lang: Locale,
  categoryMatch?: string,
  categoryMeta?: Map<string, CategoryMeta>,
): NavNode[] {
  const tree = buildNavTree(docs, lang, categoryMeta);

  // Check if there's a sidebar config for this section
  const sectionKey = categoryMatch ?? "default";
  const config = sidebars[sectionKey];

  if (!config || config.length === 0) {
    // Fall back to auto-generated
    return getNavSubtree(tree, categoryMatch);
  }

  // Resolve config to nodes
  return resolveItems(config, tree, lang);
}

function resolveItems(
  items: SidebarItem[],
  tree: NavNode[],
  lang: Locale,
): NavNode[] {
  return items.flatMap((item) => resolveItem(item, tree, lang));
}

function resolveItem(
  item: SidebarItem,
  tree: NavNode[],
  lang: Locale,
): NavNode[] {
  if (typeof item === "string") {
    // String shorthand = doc reference (always rendered as leaf, children stripped)
    const node = findNode(tree, item);
    return node ? [{ ...node, children: [] }] : [];
  }

  switch (item.type) {
    case "doc": {
      const node = findNode(tree, item.id);
      if (!node) return [];
      // Doc references always render as leaves — strip children so they
      // don't duplicate structure that the explicit config already defines.
      return [{ ...node, children: [], ...(item.label ? { label: item.label } : {}) }];
    }
    case "link": {
      return [
        {
          slug: `__link__${item.href}`,
          label: item.label,
          href: item.href,
          position: 0,
          hasPage: false,
          children: [],
        },
      ];
    }
    case "category": {
      const children = resolveItems(item.items, tree, lang);
      if (item.sortOrder === "desc") {
        children.reverse();
      }
      return [
        {
          slug: `__category__${item.label}`,
          label: item.label,
          position: 0,
          hasPage: false,
          href: undefined,
          children,
          sortOrder: item.sortOrder,
          collapsed: item.collapsed,
        },
      ];
    }
    case "autogenerated": {
      if (item.dirName) {
        const node = findNode(tree, item.dirName);
        return node ? node.children : [];
      }
      return tree;
    }
    default: {
      const _exhaustive: never = item;
      throw new Error(`Unhandled sidebar item type: ${JSON.stringify(_exhaustive)}`);
    }
  }
}
