// Monorepo-side drift/lint guard (#2921, reworked by #2946/#2947): the 3
// user-facing zudo-doc-* skills ship to consumers under
// templates/features/claudeSkills/ (npm `files` cannot reach outside the
// package dir, so scaffold.ts can no longer read the monorepo's root
// .claude/skills/ at generate time — see scaffold.ts's claudeSkills copy
// step). This file covers two independent concerns:
//
// 1. PARITY (`PARITY_SKILLS`) — skills whose template copy is still a
//    byte-mirror of its monorepo `.claude/skills/` source. This is the
//    original #2921 guard, unchanged in behavior, just re-scoped to the
//    subset of skills that haven't yet been converted to a scaffold-authored
//    variant (epic #2946). As each skill is converted, it moves OUT of
//    PARITY_SKILLS and INTO LINT_SKILLS below.
//
// 2. SCAFFOLD-CORRECTNESS LINT (`LINT_SKILLS`) — skills that HAVE been
//    converted to a scaffold-authored variant. Their template copy
//    intentionally diverges from the monorepo source (the monorepo flow
//    keeps its own script/path references; the template describes the
//    scaffold-real flow instead). What this guards is that the template
//    copy contains none of the monorepo-only references in `DENYLIST` — a
//    fresh `create-zudo-doc` project has no `scripts/version-bump.sh`, no
//    `src/config/settings.ts`, etc., so a skill referencing those paths
//    would be broken out of the box.
//
// Epic #2946 converts all 3 skills wave by wave; until every skill has
// moved to LINT_SKILLS, PARITY_SKILLS and LINT_SKILLS partition the full
// SKILLS set (every skill is in exactly one).

import { describe, it, expect, beforeAll } from "vitest";
import { execFileSync } from "node:child_process";
import fs from "fs-extra";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = path.resolve(__dirname, "../..");
const MONOREPO_ROOT = path.resolve(PKG_ROOT, "../..");

/**
 * Skills still shipped as byte-mirrors of their monorepo `.claude/skills/`
 * source — covered by the parity test below. Shrinks as each skill is
 * converted to a scaffold-authored variant (epic #2946).
 */
export const PARITY_SKILLS = ["zudo-doc-design-system", "zudo-doc-translate"];

/**
 * Skills already converted to a scaffold-authored variant — covered by the
 * scaffold-correctness lint below instead of parity. Grows as each skill is
 * converted (epic #2946); `zudo-doc-version-bump` is the Wave 1 conversion
 * (#2947).
 */
export const LINT_SKILLS = ["zudo-doc-version-bump"];

/**
 * Monorepo-only paths/idioms that must never appear in a LINT_SKILLS
 * template's SKILL.md — each exists only in this monorepo (or the
 * maintainer's personal tooling), never in a project generated by
 * create-zudo-doc.
 */
export const DENYLIST = [
  // The monorepo's own release script — a fresh scaffold has no bundled
  // version-bump script; the template describes the manual/no-script flow.
  "scripts/version-bump.sh",
  // Pre-minimal-scaffold-cutover config file — a fresh scaffold's only
  // config file is zfb.config.ts; there is no src/config/settings.ts.
  "src/config/settings.ts",
  // Monorepo showcase content directory — a fresh scaffold ships no
  // reference docs under this path.
  "src/content/docs/reference/",
  // pnpm workspace-filtering flag — only meaningful in this monorepo's
  // multi-package workspace, not in a scaffolded single-package project.
  "pnpm --filter",
  // Monorepo workspace package path — not part of a generated project.
  "packages/zudo-doc",
  // Monorepo workspace package path — not part of a generated project.
  "packages/create-zudo-doc",
  // Monorepo-root directory-scoped CLAUDE.md — a fresh scaffold's
  // generated CLAUDE.md has no such counterpart at this path.
  "src/CLAUDE.md",
  // The maintainer's personal Claude Code skill, not shipped to consumers.
  "/css-wisdom",
];

function sourcePath(skill: string): string {
  return path.join(MONOREPO_ROOT, ".claude/skills", skill, "SKILL.md");
}

function templatePath(skill: string): string {
  return path.join(
    PKG_ROOT,
    "templates/features/claudeSkills/files/.claude/skills",
    skill,
    "SKILL.md",
  );
}

describe("claudeSkills template copies match their .claude/skills/ source (#2921)", () => {
  let formatted: Record<string, { source: string; template: string }>;

  beforeAll(async () => {
    const tempDir = await fs.mkdtemp(
      path.join(os.tmpdir(), "claude-skills-drift-"),
    );
    try {
      const files: { skill: string; side: "source" | "template"; tempFile: string }[] = [];
      for (const skill of PARITY_SKILLS) {
        for (const side of ["source", "template"] as const) {
          const src = side === "source" ? sourcePath(skill) : templatePath(skill);
          const tempFile = path.join(tempDir, `${skill}-${side}.md`);
          await fs.copy(src, tempFile);
          files.push({ skill, side, tempFile });
        }
      }

      execFileSync(
        "pnpm",
        ["dlx", "@takazudo/mdx-formatter", "--write", ...files.map((f) => f.tempFile)],
        { cwd: tempDir, encoding: "utf8" },
      );

      formatted = {};
      for (const { skill, side, tempFile } of files) {
        formatted[skill] ??= { source: "", template: "" };
        formatted[skill]![side] = await fs.readFile(tempFile, "utf8");
      }
    } finally {
      await fs.remove(tempDir);
    }
  }, 60_000);

  it.each(PARITY_SKILLS)("%s template matches its monorepo source", (skill) => {
    expect(formatted[skill]!.template).toBe(formatted[skill]!.source);
  });
});

describe("claudeSkills template copies are scaffold-correct (#2946/#2947)", () => {
  it.each(LINT_SKILLS)(
    "%s template contains no monorepo-only reference",
    (skill) => {
      const content = fs.readFileSync(templatePath(skill), "utf8");
      const hits = DENYLIST.filter((entry) => content.includes(entry));
      expect(hits).toEqual([]);
    },
  );
});
